// AUTO-GENERATED by scripts/gen-i18n.mjs — do not edit.
import type { Locale } from "@/lib/i18n/config";
import type { LocalizedToolContent } from "@/lib/i18n/content/tools/types";
import { content as audioCompressorDe } from "@/lib/i18n/content/tools/audio-compressor.de";
import { content as audioCompressorEs } from "@/lib/i18n/content/tools/audio-compressor.es";
import { content as audioCompressorFr } from "@/lib/i18n/content/tools/audio-compressor.fr";
import { content as audioCompressorIt } from "@/lib/i18n/content/tools/audio-compressor.it";
import { content as audioCompressorPl } from "@/lib/i18n/content/tools/audio-compressor.pl";
import { content as audioCompressorPt } from "@/lib/i18n/content/tools/audio-compressor.pt";
import { content as audioCompressorUk } from "@/lib/i18n/content/tools/audio-compressor.uk";
import { content as compressAvifDe } from "@/lib/i18n/content/tools/compress-avif.de";
import { content as compressAvifEs } from "@/lib/i18n/content/tools/compress-avif.es";
import { content as compressAvifFr } from "@/lib/i18n/content/tools/compress-avif.fr";
import { content as compressAvifIt } from "@/lib/i18n/content/tools/compress-avif.it";
import { content as compressAvifPl } from "@/lib/i18n/content/tools/compress-avif.pl";
import { content as compressAvifPt } from "@/lib/i18n/content/tools/compress-avif.pt";
import { content as compressAvifUk } from "@/lib/i18n/content/tools/compress-avif.uk";
import { content as compressGifDe } from "@/lib/i18n/content/tools/compress-gif.de";
import { content as compressGifEs } from "@/lib/i18n/content/tools/compress-gif.es";
import { content as compressGifFr } from "@/lib/i18n/content/tools/compress-gif.fr";
import { content as compressGifIt } from "@/lib/i18n/content/tools/compress-gif.it";
import { content as compressGifPl } from "@/lib/i18n/content/tools/compress-gif.pl";
import { content as compressGifPt } from "@/lib/i18n/content/tools/compress-gif.pt";
import { content as compressGifUk } from "@/lib/i18n/content/tools/compress-gif.uk";
import { content as compressHeicDe } from "@/lib/i18n/content/tools/compress-heic.de";
import { content as compressHeicEs } from "@/lib/i18n/content/tools/compress-heic.es";
import { content as compressHeicFr } from "@/lib/i18n/content/tools/compress-heic.fr";
import { content as compressHeicIt } from "@/lib/i18n/content/tools/compress-heic.it";
import { content as compressHeicPl } from "@/lib/i18n/content/tools/compress-heic.pl";
import { content as compressHeicPt } from "@/lib/i18n/content/tools/compress-heic.pt";
import { content as compressHeicUk } from "@/lib/i18n/content/tools/compress-heic.uk";
import { content as compressJpegDe } from "@/lib/i18n/content/tools/compress-jpeg.de";
import { content as compressJpegEs } from "@/lib/i18n/content/tools/compress-jpeg.es";
import { content as compressJpegFr } from "@/lib/i18n/content/tools/compress-jpeg.fr";
import { content as compressJpegIt } from "@/lib/i18n/content/tools/compress-jpeg.it";
import { content as compressJpegPl } from "@/lib/i18n/content/tools/compress-jpeg.pl";
import { content as compressJpegPt } from "@/lib/i18n/content/tools/compress-jpeg.pt";
import { content as compressJpegUk } from "@/lib/i18n/content/tools/compress-jpeg.uk";
import { content as compressMovDe } from "@/lib/i18n/content/tools/compress-mov.de";
import { content as compressMovEs } from "@/lib/i18n/content/tools/compress-mov.es";
import { content as compressMovFr } from "@/lib/i18n/content/tools/compress-mov.fr";
import { content as compressMovIt } from "@/lib/i18n/content/tools/compress-mov.it";
import { content as compressMovPl } from "@/lib/i18n/content/tools/compress-mov.pl";
import { content as compressMovPt } from "@/lib/i18n/content/tools/compress-mov.pt";
import { content as compressMovUk } from "@/lib/i18n/content/tools/compress-mov.uk";
import { content as compressMp4De } from "@/lib/i18n/content/tools/compress-mp4.de";
import { content as compressMp4Es } from "@/lib/i18n/content/tools/compress-mp4.es";
import { content as compressMp4Fr } from "@/lib/i18n/content/tools/compress-mp4.fr";
import { content as compressMp4It } from "@/lib/i18n/content/tools/compress-mp4.it";
import { content as compressMp4Pl } from "@/lib/i18n/content/tools/compress-mp4.pl";
import { content as compressMp4Pt } from "@/lib/i18n/content/tools/compress-mp4.pt";
import { content as compressMp4Uk } from "@/lib/i18n/content/tools/compress-mp4.uk";
import { content as compressPngDe } from "@/lib/i18n/content/tools/compress-png.de";
import { content as compressPngEs } from "@/lib/i18n/content/tools/compress-png.es";
import { content as compressPngFr } from "@/lib/i18n/content/tools/compress-png.fr";
import { content as compressPngIt } from "@/lib/i18n/content/tools/compress-png.it";
import { content as compressPngPl } from "@/lib/i18n/content/tools/compress-png.pl";
import { content as compressPngPt } from "@/lib/i18n/content/tools/compress-png.pt";
import { content as compressPngUk } from "@/lib/i18n/content/tools/compress-png.uk";
import { content as compressWebpDe } from "@/lib/i18n/content/tools/compress-webp.de";
import { content as compressWebpEs } from "@/lib/i18n/content/tools/compress-webp.es";
import { content as compressWebpFr } from "@/lib/i18n/content/tools/compress-webp.fr";
import { content as compressWebpIt } from "@/lib/i18n/content/tools/compress-webp.it";
import { content as compressWebpPl } from "@/lib/i18n/content/tools/compress-webp.pl";
import { content as compressWebpPt } from "@/lib/i18n/content/tools/compress-webp.pt";
import { content as compressWebpUk } from "@/lib/i18n/content/tools/compress-webp.uk";
import { content as imageCompressorDe } from "@/lib/i18n/content/tools/image-compressor.de";
import { content as imageCompressorEs } from "@/lib/i18n/content/tools/image-compressor.es";
import { content as imageCompressorFr } from "@/lib/i18n/content/tools/image-compressor.fr";
import { content as imageCompressorIt } from "@/lib/i18n/content/tools/image-compressor.it";
import { content as imageCompressorPl } from "@/lib/i18n/content/tools/image-compressor.pl";
import { content as imageCompressorPt } from "@/lib/i18n/content/tools/image-compressor.pt";
import { content as imageCompressorUk } from "@/lib/i18n/content/tools/image-compressor.uk";
import { content as imageConverterDe } from "@/lib/i18n/content/tools/image-converter.de";
import { content as imageConverterEs } from "@/lib/i18n/content/tools/image-converter.es";
import { content as imageConverterFr } from "@/lib/i18n/content/tools/image-converter.fr";
import { content as imageConverterIt } from "@/lib/i18n/content/tools/image-converter.it";
import { content as imageConverterPl } from "@/lib/i18n/content/tools/image-converter.pl";
import { content as imageConverterPt } from "@/lib/i18n/content/tools/image-converter.pt";
import { content as imageConverterUk } from "@/lib/i18n/content/tools/image-converter.uk";
import { content as imageResizerDe } from "@/lib/i18n/content/tools/image-resizer.de";
import { content as imageResizerEs } from "@/lib/i18n/content/tools/image-resizer.es";
import { content as imageResizerFr } from "@/lib/i18n/content/tools/image-resizer.fr";
import { content as imageResizerIt } from "@/lib/i18n/content/tools/image-resizer.it";
import { content as imageResizerPl } from "@/lib/i18n/content/tools/image-resizer.pl";
import { content as imageResizerPt } from "@/lib/i18n/content/tools/image-resizer.pt";
import { content as imageResizerUk } from "@/lib/i18n/content/tools/image-resizer.uk";
import { content as pdfCompressorDe } from "@/lib/i18n/content/tools/pdf-compressor.de";
import { content as pdfCompressorEs } from "@/lib/i18n/content/tools/pdf-compressor.es";
import { content as pdfCompressorFr } from "@/lib/i18n/content/tools/pdf-compressor.fr";
import { content as pdfCompressorIt } from "@/lib/i18n/content/tools/pdf-compressor.it";
import { content as pdfCompressorPl } from "@/lib/i18n/content/tools/pdf-compressor.pl";
import { content as pdfCompressorPt } from "@/lib/i18n/content/tools/pdf-compressor.pt";
import { content as pdfCompressorUk } from "@/lib/i18n/content/tools/pdf-compressor.uk";
import { content as videoCompressorDe } from "@/lib/i18n/content/tools/video-compressor.de";
import { content as videoCompressorEs } from "@/lib/i18n/content/tools/video-compressor.es";
import { content as videoCompressorFr } from "@/lib/i18n/content/tools/video-compressor.fr";
import { content as videoCompressorIt } from "@/lib/i18n/content/tools/video-compressor.it";
import { content as videoCompressorPl } from "@/lib/i18n/content/tools/video-compressor.pl";
import { content as videoCompressorPt } from "@/lib/i18n/content/tools/video-compressor.pt";
import { content as videoCompressorUk } from "@/lib/i18n/content/tools/video-compressor.uk";

export const TOOL_REGISTRY: Partial<Record<Locale, Record<string, LocalizedToolContent>>> = {
  de: {
    "audio-compressor": audioCompressorDe,
    "compress-avif": compressAvifDe,
    "compress-gif": compressGifDe,
    "compress-heic": compressHeicDe,
    "compress-jpeg": compressJpegDe,
    "compress-mov": compressMovDe,
    "compress-mp4": compressMp4De,
    "compress-png": compressPngDe,
    "compress-webp": compressWebpDe,
    "image-compressor": imageCompressorDe,
    "image-converter": imageConverterDe,
    "image-resizer": imageResizerDe,
    "pdf-compressor": pdfCompressorDe,
    "video-compressor": videoCompressorDe,
  },
  es: {
    "audio-compressor": audioCompressorEs,
    "compress-avif": compressAvifEs,
    "compress-gif": compressGifEs,
    "compress-heic": compressHeicEs,
    "compress-jpeg": compressJpegEs,
    "compress-mov": compressMovEs,
    "compress-mp4": compressMp4Es,
    "compress-png": compressPngEs,
    "compress-webp": compressWebpEs,
    "image-compressor": imageCompressorEs,
    "image-converter": imageConverterEs,
    "image-resizer": imageResizerEs,
    "pdf-compressor": pdfCompressorEs,
    "video-compressor": videoCompressorEs,
  },
  fr: {
    "audio-compressor": audioCompressorFr,
    "compress-avif": compressAvifFr,
    "compress-gif": compressGifFr,
    "compress-heic": compressHeicFr,
    "compress-jpeg": compressJpegFr,
    "compress-mov": compressMovFr,
    "compress-mp4": compressMp4Fr,
    "compress-png": compressPngFr,
    "compress-webp": compressWebpFr,
    "image-compressor": imageCompressorFr,
    "image-converter": imageConverterFr,
    "image-resizer": imageResizerFr,
    "pdf-compressor": pdfCompressorFr,
    "video-compressor": videoCompressorFr,
  },
  it: {
    "audio-compressor": audioCompressorIt,
    "compress-avif": compressAvifIt,
    "compress-gif": compressGifIt,
    "compress-heic": compressHeicIt,
    "compress-jpeg": compressJpegIt,
    "compress-mov": compressMovIt,
    "compress-mp4": compressMp4It,
    "compress-png": compressPngIt,
    "compress-webp": compressWebpIt,
    "image-compressor": imageCompressorIt,
    "image-converter": imageConverterIt,
    "image-resizer": imageResizerIt,
    "pdf-compressor": pdfCompressorIt,
    "video-compressor": videoCompressorIt,
  },
  pl: {
    "audio-compressor": audioCompressorPl,
    "compress-avif": compressAvifPl,
    "compress-gif": compressGifPl,
    "compress-heic": compressHeicPl,
    "compress-jpeg": compressJpegPl,
    "compress-mov": compressMovPl,
    "compress-mp4": compressMp4Pl,
    "compress-png": compressPngPl,
    "compress-webp": compressWebpPl,
    "image-compressor": imageCompressorPl,
    "image-converter": imageConverterPl,
    "image-resizer": imageResizerPl,
    "pdf-compressor": pdfCompressorPl,
    "video-compressor": videoCompressorPl,
  },
  pt: {
    "audio-compressor": audioCompressorPt,
    "compress-avif": compressAvifPt,
    "compress-gif": compressGifPt,
    "compress-heic": compressHeicPt,
    "compress-jpeg": compressJpegPt,
    "compress-mov": compressMovPt,
    "compress-mp4": compressMp4Pt,
    "compress-png": compressPngPt,
    "compress-webp": compressWebpPt,
    "image-compressor": imageCompressorPt,
    "image-converter": imageConverterPt,
    "image-resizer": imageResizerPt,
    "pdf-compressor": pdfCompressorPt,
    "video-compressor": videoCompressorPt,
  },
  uk: {
    "audio-compressor": audioCompressorUk,
    "compress-avif": compressAvifUk,
    "compress-gif": compressGifUk,
    "compress-heic": compressHeicUk,
    "compress-jpeg": compressJpegUk,
    "compress-mov": compressMovUk,
    "compress-mp4": compressMp4Uk,
    "compress-png": compressPngUk,
    "compress-webp": compressWebpUk,
    "image-compressor": imageCompressorUk,
    "image-converter": imageConverterUk,
    "image-resizer": imageResizerUk,
    "pdf-compressor": pdfCompressorUk,
    "video-compressor": videoCompressorUk,
  },
};
