// AUTO-GENERATED by scripts/gen-i18n.mjs — do not edit.
import type { Locale } from "@/lib/i18n/config";
import type { LocalizedContentPage } from "@/lib/i18n/content/pages/types";
import { content as aboutDe } from "@/lib/i18n/content/pages/about.de";
import { content as aboutEs } from "@/lib/i18n/content/pages/about.es";
import { content as aboutFr } from "@/lib/i18n/content/pages/about.fr";
import { content as aboutIt } from "@/lib/i18n/content/pages/about.it";
import { content as aboutPl } from "@/lib/i18n/content/pages/about.pl";
import { content as aboutPt } from "@/lib/i18n/content/pages/about.pt";
import { content as aboutUk } from "@/lib/i18n/content/pages/about.uk";
import { content as contactDe } from "@/lib/i18n/content/pages/contact.de";
import { content as contactEs } from "@/lib/i18n/content/pages/contact.es";
import { content as contactFr } from "@/lib/i18n/content/pages/contact.fr";
import { content as contactIt } from "@/lib/i18n/content/pages/contact.it";
import { content as contactPl } from "@/lib/i18n/content/pages/contact.pl";
import { content as contactPt } from "@/lib/i18n/content/pages/contact.pt";
import { content as contactUk } from "@/lib/i18n/content/pages/contact.uk";
import { content as cookiePolicyDe } from "@/lib/i18n/content/pages/cookie-policy.de";
import { content as cookiePolicyEs } from "@/lib/i18n/content/pages/cookie-policy.es";
import { content as cookiePolicyFr } from "@/lib/i18n/content/pages/cookie-policy.fr";
import { content as cookiePolicyIt } from "@/lib/i18n/content/pages/cookie-policy.it";
import { content as cookiePolicyPl } from "@/lib/i18n/content/pages/cookie-policy.pl";
import { content as cookiePolicyPt } from "@/lib/i18n/content/pages/cookie-policy.pt";
import { content as cookiePolicyUk } from "@/lib/i18n/content/pages/cookie-policy.uk";
import { content as disclaimerDe } from "@/lib/i18n/content/pages/disclaimer.de";
import { content as disclaimerEs } from "@/lib/i18n/content/pages/disclaimer.es";
import { content as disclaimerFr } from "@/lib/i18n/content/pages/disclaimer.fr";
import { content as disclaimerIt } from "@/lib/i18n/content/pages/disclaimer.it";
import { content as disclaimerPl } from "@/lib/i18n/content/pages/disclaimer.pl";
import { content as disclaimerPt } from "@/lib/i18n/content/pages/disclaimer.pt";
import { content as disclaimerUk } from "@/lib/i18n/content/pages/disclaimer.uk";
import { content as privacyPolicyDe } from "@/lib/i18n/content/pages/privacy-policy.de";
import { content as privacyPolicyEs } from "@/lib/i18n/content/pages/privacy-policy.es";
import { content as privacyPolicyFr } from "@/lib/i18n/content/pages/privacy-policy.fr";
import { content as privacyPolicyIt } from "@/lib/i18n/content/pages/privacy-policy.it";
import { content as privacyPolicyPl } from "@/lib/i18n/content/pages/privacy-policy.pl";
import { content as privacyPolicyPt } from "@/lib/i18n/content/pages/privacy-policy.pt";
import { content as privacyPolicyUk } from "@/lib/i18n/content/pages/privacy-policy.uk";
import { content as termsOfServiceDe } from "@/lib/i18n/content/pages/terms-of-service.de";
import { content as termsOfServiceEs } from "@/lib/i18n/content/pages/terms-of-service.es";
import { content as termsOfServiceFr } from "@/lib/i18n/content/pages/terms-of-service.fr";
import { content as termsOfServiceIt } from "@/lib/i18n/content/pages/terms-of-service.it";
import { content as termsOfServicePl } from "@/lib/i18n/content/pages/terms-of-service.pl";
import { content as termsOfServicePt } from "@/lib/i18n/content/pages/terms-of-service.pt";
import { content as termsOfServiceUk } from "@/lib/i18n/content/pages/terms-of-service.uk";

export const PAGE_REGISTRY: Partial<Record<Locale, Record<string, LocalizedContentPage>>> = {
  de: {
    "about": aboutDe,
    "contact": contactDe,
    "cookie-policy": cookiePolicyDe,
    "disclaimer": disclaimerDe,
    "privacy-policy": privacyPolicyDe,
    "terms-of-service": termsOfServiceDe,
  },
  es: {
    "about": aboutEs,
    "contact": contactEs,
    "cookie-policy": cookiePolicyEs,
    "disclaimer": disclaimerEs,
    "privacy-policy": privacyPolicyEs,
    "terms-of-service": termsOfServiceEs,
  },
  fr: {
    "about": aboutFr,
    "contact": contactFr,
    "cookie-policy": cookiePolicyFr,
    "disclaimer": disclaimerFr,
    "privacy-policy": privacyPolicyFr,
    "terms-of-service": termsOfServiceFr,
  },
  it: {
    "about": aboutIt,
    "contact": contactIt,
    "cookie-policy": cookiePolicyIt,
    "disclaimer": disclaimerIt,
    "privacy-policy": privacyPolicyIt,
    "terms-of-service": termsOfServiceIt,
  },
  pl: {
    "about": aboutPl,
    "contact": contactPl,
    "cookie-policy": cookiePolicyPl,
    "disclaimer": disclaimerPl,
    "privacy-policy": privacyPolicyPl,
    "terms-of-service": termsOfServicePl,
  },
  pt: {
    "about": aboutPt,
    "contact": contactPt,
    "cookie-policy": cookiePolicyPt,
    "disclaimer": disclaimerPt,
    "privacy-policy": privacyPolicyPt,
    "terms-of-service": termsOfServicePt,
  },
  uk: {
    "about": aboutUk,
    "contact": contactUk,
    "cookie-policy": cookiePolicyUk,
    "disclaimer": disclaimerUk,
    "privacy-policy": privacyPolicyUk,
    "terms-of-service": termsOfServiceUk,
  },
};
