// AUTO-GENERATED by scripts/gen-i18n.mjs — do not edit.
import type { BlogPost, BlogPostModule } from "@/lib/blog/types";
import * as bestImageFormatsForTheWeb2026De from "@/components/blog/posts/best-image-formats-for-the-web-2026.de";
import * as bestImageFormatsForTheWeb2026Es from "@/components/blog/posts/best-image-formats-for-the-web-2026.es";
import * as bestImageFormatsForTheWeb2026Fr from "@/components/blog/posts/best-image-formats-for-the-web-2026.fr";
import * as bestImageFormatsForTheWeb2026It from "@/components/blog/posts/best-image-formats-for-the-web-2026.it";
import * as bestImageFormatsForTheWeb2026Pl from "@/components/blog/posts/best-image-formats-for-the-web-2026.pl";
import * as bestImageFormatsForTheWeb2026Pt from "@/components/blog/posts/best-image-formats-for-the-web-2026.pt";
import * as bestImageFormatsForTheWeb2026Uk from "@/components/blog/posts/best-image-formats-for-the-web-2026.uk";
import * as compressImagesWithoutLosingQualityDe from "@/components/blog/posts/compress-images-without-losing-quality.de";
import * as compressImagesWithoutLosingQualityEs from "@/components/blog/posts/compress-images-without-losing-quality.es";
import * as compressImagesWithoutLosingQualityFr from "@/components/blog/posts/compress-images-without-losing-quality.fr";
import * as compressImagesWithoutLosingQualityIt from "@/components/blog/posts/compress-images-without-losing-quality.it";
import * as compressImagesWithoutLosingQualityPl from "@/components/blog/posts/compress-images-without-losing-quality.pl";
import * as compressImagesWithoutLosingQualityPt from "@/components/blog/posts/compress-images-without-losing-quality.pt";
import * as compressImagesWithoutLosingQualityUk from "@/components/blog/posts/compress-images-without-losing-quality.uk";
import * as howClientSideFileCompressionWorksDe from "@/components/blog/posts/how-client-side-file-compression-works.de";
import * as howClientSideFileCompressionWorksEs from "@/components/blog/posts/how-client-side-file-compression-works.es";
import * as howClientSideFileCompressionWorksFr from "@/components/blog/posts/how-client-side-file-compression-works.fr";
import * as howClientSideFileCompressionWorksIt from "@/components/blog/posts/how-client-side-file-compression-works.it";
import * as howClientSideFileCompressionWorksPl from "@/components/blog/posts/how-client-side-file-compression-works.pl";
import * as howClientSideFileCompressionWorksPt from "@/components/blog/posts/how-client-side-file-compression-works.pt";
import * as howClientSideFileCompressionWorksUk from "@/components/blog/posts/how-client-side-file-compression-works.uk";
import * as howToCompressAudioFilesDe from "@/components/blog/posts/how-to-compress-audio-files.de";
import * as howToCompressAudioFilesEs from "@/components/blog/posts/how-to-compress-audio-files.es";
import * as howToCompressAudioFilesFr from "@/components/blog/posts/how-to-compress-audio-files.fr";
import * as howToCompressAudioFilesIt from "@/components/blog/posts/how-to-compress-audio-files.it";
import * as howToCompressAudioFilesPl from "@/components/blog/posts/how-to-compress-audio-files.pl";
import * as howToCompressAudioFilesPt from "@/components/blog/posts/how-to-compress-audio-files.pt";
import * as howToCompressAudioFilesUk from "@/components/blog/posts/how-to-compress-audio-files.uk";
import * as howToCompressVideoForEmailAndWebDe from "@/components/blog/posts/how-to-compress-video-for-email-and-web.de";
import * as howToCompressVideoForEmailAndWebEs from "@/components/blog/posts/how-to-compress-video-for-email-and-web.es";
import * as howToCompressVideoForEmailAndWebFr from "@/components/blog/posts/how-to-compress-video-for-email-and-web.fr";
import * as howToCompressVideoForEmailAndWebIt from "@/components/blog/posts/how-to-compress-video-for-email-and-web.it";
import * as howToCompressVideoForEmailAndWebPl from "@/components/blog/posts/how-to-compress-video-for-email-and-web.pl";
import * as howToCompressVideoForEmailAndWebPt from "@/components/blog/posts/how-to-compress-video-for-email-and-web.pt";
import * as howToCompressVideoForEmailAndWebUk from "@/components/blog/posts/how-to-compress-video-for-email-and-web.uk";
import * as isItSafeToCompressFilesOnlineDe from "@/components/blog/posts/is-it-safe-to-compress-files-online.de";
import * as isItSafeToCompressFilesOnlineEs from "@/components/blog/posts/is-it-safe-to-compress-files-online.es";
import * as isItSafeToCompressFilesOnlineFr from "@/components/blog/posts/is-it-safe-to-compress-files-online.fr";
import * as isItSafeToCompressFilesOnlineIt from "@/components/blog/posts/is-it-safe-to-compress-files-online.it";
import * as isItSafeToCompressFilesOnlinePl from "@/components/blog/posts/is-it-safe-to-compress-files-online.pl";
import * as isItSafeToCompressFilesOnlinePt from "@/components/blog/posts/is-it-safe-to-compress-files-online.pt";
import * as isItSafeToCompressFilesOnlineUk from "@/components/blog/posts/is-it-safe-to-compress-files-online.uk";
import * as jpegVsPngVsWebpVsAvifDe from "@/components/blog/posts/jpeg-vs-png-vs-webp-vs-avif.de";
import * as jpegVsPngVsWebpVsAvifEs from "@/components/blog/posts/jpeg-vs-png-vs-webp-vs-avif.es";
import * as jpegVsPngVsWebpVsAvifFr from "@/components/blog/posts/jpeg-vs-png-vs-webp-vs-avif.fr";
import * as jpegVsPngVsWebpVsAvifIt from "@/components/blog/posts/jpeg-vs-png-vs-webp-vs-avif.it";
import * as jpegVsPngVsWebpVsAvifPl from "@/components/blog/posts/jpeg-vs-png-vs-webp-vs-avif.pl";
import * as jpegVsPngVsWebpVsAvifPt from "@/components/blog/posts/jpeg-vs-png-vs-webp-vs-avif.pt";
import * as jpegVsPngVsWebpVsAvifUk from "@/components/blog/posts/jpeg-vs-png-vs-webp-vs-avif.uk";
import * as lossyVsLosslessDe from "@/components/blog/posts/lossy-vs-lossless.de";
import * as lossyVsLosslessEs from "@/components/blog/posts/lossy-vs-lossless.es";
import * as lossyVsLosslessFr from "@/components/blog/posts/lossy-vs-lossless.fr";
import * as lossyVsLosslessIt from "@/components/blog/posts/lossy-vs-lossless.it";
import * as lossyVsLosslessPl from "@/components/blog/posts/lossy-vs-lossless.pl";
import * as lossyVsLosslessPt from "@/components/blog/posts/lossy-vs-lossless.pt";
import * as lossyVsLosslessUk from "@/components/blog/posts/lossy-vs-lossless.uk";
import * as mp4VsWebmVsMovVsMkvDe from "@/components/blog/posts/mp4-vs-webm-vs-mov-vs-mkv.de";
import * as mp4VsWebmVsMovVsMkvEs from "@/components/blog/posts/mp4-vs-webm-vs-mov-vs-mkv.es";
import * as mp4VsWebmVsMovVsMkvFr from "@/components/blog/posts/mp4-vs-webm-vs-mov-vs-mkv.fr";
import * as mp4VsWebmVsMovVsMkvIt from "@/components/blog/posts/mp4-vs-webm-vs-mov-vs-mkv.it";
import * as mp4VsWebmVsMovVsMkvPl from "@/components/blog/posts/mp4-vs-webm-vs-mov-vs-mkv.pl";
import * as mp4VsWebmVsMovVsMkvPt from "@/components/blog/posts/mp4-vs-webm-vs-mov-vs-mkv.pt";
import * as mp4VsWebmVsMovVsMkvUk from "@/components/blog/posts/mp4-vs-webm-vs-mov-vs-mkv.uk";
import * as whatIsWebpAndShouldYouUseItDe from "@/components/blog/posts/what-is-webp-and-should-you-use-it.de";
import * as whatIsWebpAndShouldYouUseItEs from "@/components/blog/posts/what-is-webp-and-should-you-use-it.es";
import * as whatIsWebpAndShouldYouUseItFr from "@/components/blog/posts/what-is-webp-and-should-you-use-it.fr";
import * as whatIsWebpAndShouldYouUseItIt from "@/components/blog/posts/what-is-webp-and-should-you-use-it.it";
import * as whatIsWebpAndShouldYouUseItPl from "@/components/blog/posts/what-is-webp-and-should-you-use-it.pl";
import * as whatIsWebpAndShouldYouUseItPt from "@/components/blog/posts/what-is-webp-and-should-you-use-it.pt";
import * as whatIsWebpAndShouldYouUseItUk from "@/components/blog/posts/what-is-webp-and-should-you-use-it.uk";
import * as whyIsMyPdfSoBigDe from "@/components/blog/posts/why-is-my-pdf-so-big.de";
import * as whyIsMyPdfSoBigEs from "@/components/blog/posts/why-is-my-pdf-so-big.es";
import * as whyIsMyPdfSoBigFr from "@/components/blog/posts/why-is-my-pdf-so-big.fr";
import * as whyIsMyPdfSoBigIt from "@/components/blog/posts/why-is-my-pdf-so-big.it";
import * as whyIsMyPdfSoBigPl from "@/components/blog/posts/why-is-my-pdf-so-big.pl";
import * as whyIsMyPdfSoBigPt from "@/components/blog/posts/why-is-my-pdf-so-big.pt";
import * as whyIsMyPdfSoBigUk from "@/components/blog/posts/why-is-my-pdf-so-big.uk";

function build(mods: BlogPostModule[]): BlogPost[] {
  return mods
    .map((m) => ({ ...m.meta, Content: m.default }))
    .sort((a, b) => b.datePublished.localeCompare(a.datePublished));
}

export const POSTS_BY_LOCALE: Partial<Record<string, BlogPost[]>> = {
  de: build([bestImageFormatsForTheWeb2026De as unknown as BlogPostModule, compressImagesWithoutLosingQualityDe as unknown as BlogPostModule, howClientSideFileCompressionWorksDe as unknown as BlogPostModule, howToCompressAudioFilesDe as unknown as BlogPostModule, howToCompressVideoForEmailAndWebDe as unknown as BlogPostModule, isItSafeToCompressFilesOnlineDe as unknown as BlogPostModule, jpegVsPngVsWebpVsAvifDe as unknown as BlogPostModule, lossyVsLosslessDe as unknown as BlogPostModule, mp4VsWebmVsMovVsMkvDe as unknown as BlogPostModule, whatIsWebpAndShouldYouUseItDe as unknown as BlogPostModule, whyIsMyPdfSoBigDe as unknown as BlogPostModule]),
  es: build([bestImageFormatsForTheWeb2026Es as unknown as BlogPostModule, compressImagesWithoutLosingQualityEs as unknown as BlogPostModule, howClientSideFileCompressionWorksEs as unknown as BlogPostModule, howToCompressAudioFilesEs as unknown as BlogPostModule, howToCompressVideoForEmailAndWebEs as unknown as BlogPostModule, isItSafeToCompressFilesOnlineEs as unknown as BlogPostModule, jpegVsPngVsWebpVsAvifEs as unknown as BlogPostModule, lossyVsLosslessEs as unknown as BlogPostModule, mp4VsWebmVsMovVsMkvEs as unknown as BlogPostModule, whatIsWebpAndShouldYouUseItEs as unknown as BlogPostModule, whyIsMyPdfSoBigEs as unknown as BlogPostModule]),
  fr: build([bestImageFormatsForTheWeb2026Fr as unknown as BlogPostModule, compressImagesWithoutLosingQualityFr as unknown as BlogPostModule, howClientSideFileCompressionWorksFr as unknown as BlogPostModule, howToCompressAudioFilesFr as unknown as BlogPostModule, howToCompressVideoForEmailAndWebFr as unknown as BlogPostModule, isItSafeToCompressFilesOnlineFr as unknown as BlogPostModule, jpegVsPngVsWebpVsAvifFr as unknown as BlogPostModule, lossyVsLosslessFr as unknown as BlogPostModule, mp4VsWebmVsMovVsMkvFr as unknown as BlogPostModule, whatIsWebpAndShouldYouUseItFr as unknown as BlogPostModule, whyIsMyPdfSoBigFr as unknown as BlogPostModule]),
  it: build([bestImageFormatsForTheWeb2026It as unknown as BlogPostModule, compressImagesWithoutLosingQualityIt as unknown as BlogPostModule, howClientSideFileCompressionWorksIt as unknown as BlogPostModule, howToCompressAudioFilesIt as unknown as BlogPostModule, howToCompressVideoForEmailAndWebIt as unknown as BlogPostModule, isItSafeToCompressFilesOnlineIt as unknown as BlogPostModule, jpegVsPngVsWebpVsAvifIt as unknown as BlogPostModule, lossyVsLosslessIt as unknown as BlogPostModule, mp4VsWebmVsMovVsMkvIt as unknown as BlogPostModule, whatIsWebpAndShouldYouUseItIt as unknown as BlogPostModule, whyIsMyPdfSoBigIt as unknown as BlogPostModule]),
  pl: build([bestImageFormatsForTheWeb2026Pl as unknown as BlogPostModule, compressImagesWithoutLosingQualityPl as unknown as BlogPostModule, howClientSideFileCompressionWorksPl as unknown as BlogPostModule, howToCompressAudioFilesPl as unknown as BlogPostModule, howToCompressVideoForEmailAndWebPl as unknown as BlogPostModule, isItSafeToCompressFilesOnlinePl as unknown as BlogPostModule, jpegVsPngVsWebpVsAvifPl as unknown as BlogPostModule, lossyVsLosslessPl as unknown as BlogPostModule, mp4VsWebmVsMovVsMkvPl as unknown as BlogPostModule, whatIsWebpAndShouldYouUseItPl as unknown as BlogPostModule, whyIsMyPdfSoBigPl as unknown as BlogPostModule]),
  pt: build([bestImageFormatsForTheWeb2026Pt as unknown as BlogPostModule, compressImagesWithoutLosingQualityPt as unknown as BlogPostModule, howClientSideFileCompressionWorksPt as unknown as BlogPostModule, howToCompressAudioFilesPt as unknown as BlogPostModule, howToCompressVideoForEmailAndWebPt as unknown as BlogPostModule, isItSafeToCompressFilesOnlinePt as unknown as BlogPostModule, jpegVsPngVsWebpVsAvifPt as unknown as BlogPostModule, lossyVsLosslessPt as unknown as BlogPostModule, mp4VsWebmVsMovVsMkvPt as unknown as BlogPostModule, whatIsWebpAndShouldYouUseItPt as unknown as BlogPostModule, whyIsMyPdfSoBigPt as unknown as BlogPostModule]),
  uk: build([bestImageFormatsForTheWeb2026Uk as unknown as BlogPostModule, compressImagesWithoutLosingQualityUk as unknown as BlogPostModule, howClientSideFileCompressionWorksUk as unknown as BlogPostModule, howToCompressAudioFilesUk as unknown as BlogPostModule, howToCompressVideoForEmailAndWebUk as unknown as BlogPostModule, isItSafeToCompressFilesOnlineUk as unknown as BlogPostModule, jpegVsPngVsWebpVsAvifUk as unknown as BlogPostModule, lossyVsLosslessUk as unknown as BlogPostModule, mp4VsWebmVsMovVsMkvUk as unknown as BlogPostModule, whatIsWebpAndShouldYouUseItUk as unknown as BlogPostModule, whyIsMyPdfSoBigUk as unknown as BlogPostModule]),
};
