// Regenerates the locale CONTENT registries from the filesystem so adding a
// language is just "drop in the per-locale files + run this".
//
//   node scripts/gen-i18n.mjs
//
// Emits (auto-generated, do not edit by hand):
//   lib/i18n/content/tools/registry.generated.ts   (TOOL_REGISTRY)
//   lib/i18n/content/pages/registry.generated.ts   (PAGE_REGISTRY)
//   lib/blog/posts.generated.ts                     (POSTS_BY_LOCALE)
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const LOCALES = ["es", "pt", "it", "de", "fr", "pl", "uk"];
const LOCALE_RE = new RegExp(`\\.(${LOCALES.join("|")})\\.tsx$`);

const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const ident = (slug, loc) =>
  slug.replace(/[-.](\w)/g, (_, c) => c.toUpperCase()).replace(/\W/g, "") +
  cap(loc);

/** Collect `{ slug, locale, file }` for a directory of `<slug>.<loc>.tsx`. */
function collect(dir) {
  const out = [];
  for (const f of fs.readdirSync(path.join(ROOT, dir))) {
    const m = f.match(LOCALE_RE);
    if (!m) continue;
    const locale = m[1];
    const slug = f.slice(0, f.length - `.${locale}.tsx`.length);
    out.push({ slug, locale, base: f.replace(/\.tsx$/, "") });
  }
  return out.sort((a, b) => a.base.localeCompare(b.base));
}

function byLocale(entries) {
  const map = {};
  for (const e of entries) (map[e.locale] ??= []).push(e);
  return map;
}

const banner = "// AUTO-GENERATED by scripts/gen-i18n.mjs — do not edit.\n";

// ---- tools + pages (same shape: `export const content`) ----
function genContentRegistry({ dir, importAlias, typeName, typeImport, constName }) {
  const entries = collect(dir);
  const imports = entries
    .map(
      (e) =>
        `import { content as ${ident(e.slug, e.locale)} } from "${importAlias}/${e.base}";`,
    )
    .join("\n");
  const grouped = byLocale(entries);
  const maps = Object.keys(grouped)
    .map((loc) => {
      const body = grouped[loc]
        .map((e) => `    ${JSON.stringify(e.slug)}: ${ident(e.slug, loc)},`)
        .join("\n");
      return `  ${loc}: {\n${body}\n  },`;
    })
    .join("\n");
  return `${banner}import type { Locale } from "@/lib/i18n/config";
import type { ${typeName} } from "${typeImport}";
${imports}

export const ${constName}: Partial<Record<Locale, Record<string, ${typeName}>>> = {
${maps}
};
`;
}

fs.writeFileSync(
  path.join(ROOT, "lib/i18n/content/tools/registry.generated.ts"),
  genContentRegistry({
    dir: "lib/i18n/content/tools",
    importAlias: "@/lib/i18n/content/tools",
    typeName: "LocalizedToolContent",
    typeImport: "@/lib/i18n/content/tools/types",
    constName: "TOOL_REGISTRY",
  }),
);

fs.writeFileSync(
  path.join(ROOT, "lib/i18n/content/pages/registry.generated.ts"),
  genContentRegistry({
    dir: "lib/i18n/content/pages",
    importAlias: "@/lib/i18n/content/pages",
    typeName: "LocalizedContentPage",
    typeImport: "@/lib/i18n/content/pages/types",
    constName: "PAGE_REGISTRY",
  }),
);

// ---- blog posts (module: meta + default Content) ----
{
  const entries = collect("components/blog/posts");
  const imports = entries
    .map(
      (e) =>
        `import * as ${ident(e.slug, e.locale)} from "@/components/blog/posts/${e.base}";`,
    )
    .join("\n");
  const grouped = byLocale(entries);
  const maps = Object.keys(grouped)
    .map((loc) => {
      const list = grouped[loc]
        .map((e) => `${ident(e.slug, loc)} as unknown as BlogPostModule`)
        .join(", ");
      return `  ${loc}: build([${list}]),`;
    })
    .join("\n");
  const out = `${banner}import type { BlogPost, BlogPostModule } from "@/lib/blog/types";
${imports}

function build(mods: BlogPostModule[]): BlogPost[] {
  return mods
    .map((m) => ({ ...m.meta, Content: m.default }))
    .sort((a, b) => b.datePublished.localeCompare(a.datePublished));
}

export const POSTS_BY_LOCALE: Partial<Record<string, BlogPost[]>> = {
${maps}
};
`;
  fs.writeFileSync(path.join(ROOT, "lib/blog/posts.generated.ts"), out);
}

console.log("i18n registries generated.");
