// ─── Daily blog generator ─────────────────────────────────────────────────────
// Generates N brand-new blog posts with the Claude API, matching the existing
// posts' voice, structure, length, and on-page SEO, then writes them into THIS
// repo's source of truth:
//
//   English post      → components/blog/posts/<slug>.tsx   (TSX module:
//                        `export const meta` + default `Content` component)
//   Registry          → lib/blog/registry.ts               (import + MODULES entry;
//                        this is what makes the post appear on /blog AND in the
//                        sitemap, which both derive from POSTS)
//   Translations      → components/blog/posts/<slug>.<loc>.tsx  (one per locale)
//   Generated index   → lib/blog/posts.generated.ts         (regenerated by
//                        running scripts/gen-i18n.mjs — picks up the .<loc>.tsx
//                        files from the filesystem automatically)
//
// A push of those changes to `main` triggers the production deploy and the
// IndexNow ping (see scripts/indexnow.mjs / changed-urls.mjs).
//
// The article body is JSX (this repo renders React post components, not
// markdown). The model returns a restricted JSX subset — <p>, <h2 id>, <h3 id>,
// <ul>/<li>, <strong>, <em>, <code>, <Link href> (internal) and <a href> with
// target/rel (external) — matching the existing posts. We validate the body
// against that allow-list before writing.
//
// Usage:
//   node scripts/generate-blog.mjs              # generate 2 posts, write files
//   node scripts/generate-blog.mjs --count 1    # generate 1 post
//   node scripts/generate-blog.mjs --no-write   # generate + print, write nothing
//
// Env:
//   ANTHROPIC_API_KEY   required — the Claude API key
//   ANTHROPIC_MODEL     optional — defaults to "claude-opus-4-8"
//
// Dependency-free: Node 20+ global fetch, no npm packages (like indexnow.mjs).

import { readFile, writeFile, readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// Non-default locales (English lives at the root with no prefix).
// Keep in sync with lib/i18n/config.ts LOCALES and scripts/gen-i18n.mjs.
const LOCALES = ["es", "pt", "it", "de", "fr", "pl", "uk"];
const LOCALE_NAMES = {
    es: "Spanish", pt: "Portuguese", it: "Italian", de: "German",
    fr: "French", pl: "Polish", uk: "Ukrainian",
};

const MODEL = process.env.ANTHROPIC_MODEL || "claude-opus-4-8";
const API_KEY = process.env.ANTHROPIC_API_KEY;

const args = process.argv.slice(2);
const countIdx = args.indexOf("--count");
const COUNT = countIdx >= 0 && Number(args[countIdx + 1]) > 0 ? Number(args[countIdx + 1]) : 2;
const NO_WRITE = args.includes("--no-write");

const POSTS_DIR = path.join(ROOT, "components/blog/posts");
const REGISTRY_TS = path.join(ROOT, "lib/blog/registry.ts");
const postFile = (slug, loc) =>
    path.join(POSTS_DIR, loc ? `${slug}.${loc}.tsx` : `${slug}.tsx`);

// Known author ids (see lib/blog/authors.ts).
const AUTHOR_IDS = ["team", "maya"];

// JSON Schema for one post object (meta fields + a JSX body string).
const POST_SCHEMA = {
    type: "object",
    properties: {
        slug: { type: "string" },
        title: { type: "string" },
        description: { type: "string" },
        authorId: { type: "string", enum: AUTHOR_IDS },
        tags: { type: "array", items: { type: "string" } },
        readingMinutes: { type: "integer" },
        body: { type: "string" },
    },
    required: ["slug", "title", "description", "authorId", "tags", "readingMinutes", "body"],
};

const POSTS_TOOL = {
    name: "submit_posts",
    description: "Submit the finished blog post objects.",
    input_schema: {
        type: "object",
        properties: { posts: { type: "array", items: POST_SCHEMA } },
        required: ["posts"],
    },
};

// ─── Anthropic Messages API (tool use → structured, valid JSON) ───────────────
async function claudePosts(prompt, maxTokens = 16000) {
    if (!API_KEY) throw new Error("ANTHROPIC_API_KEY is not set");
    const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
            "x-api-key": API_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        body: JSON.stringify({
            model: MODEL,
            max_tokens: maxTokens,
            tools: [POSTS_TOOL],
            tool_choice: { type: "tool", name: "submit_posts" },
            messages: [{ role: "user", content: prompt }],
        }),
    });
    if (!res.ok) {
        const text = await res.text();
        throw new Error(`Anthropic API ${res.status}: ${text.slice(0, 500)}`);
    }
    const data = await res.json();
    const tool = (data.content || []).find((b) => b.type === "tool_use");
    if (!tool || !Array.isArray(tool.input?.posts)) {
        throw new Error(`Model did not return posts (stop_reason: ${data.stop_reason})`);
    }
    return tool.input.posts;
}

// ─── Read existing English posts (for style samples + existing slugs) ─────────
// Each English post is `<slug>.tsx` (no locale segment). We pull the `meta`
// fields with light regex and the JSX body between the `return (` and the final
// `);` of the Content component.
function parseMeta(src) {
    const grab = (key) => {
        const m = src.match(new RegExp(`${key}:\\s*"((?:[^"\\\\]|\\\\.)*)"`));
        return m ? m[1].replace(/\\"/g, '"') : undefined;
    };
    const slug = grab("slug");
    const title = grab("title");
    const description = grab("description");
    const authorId = grab("authorId");
    const rm = src.match(/readingMinutes:\s*(\d+)/);
    const tagsM = src.match(/tags:\s*\[([^\]]*)\]/);
    const tags = tagsM
        ? tagsM[1].split(",").map((s) => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean)
        : [];
    return {
        slug, title, description, authorId,
        readingMinutes: rm ? Number(rm[1]) : 6,
        tags,
    };
}

function extractBody(src) {
    const start = src.indexOf("return (");
    if (start < 0) return "";
    const open = src.indexOf("<>", start);
    const close = src.lastIndexOf("</>");
    if (open < 0 || close < 0 || close <= open) return "";
    return src.slice(open + 2, close).trim();
}

async function readEnglishPosts() {
    const files = await readdir(POSTS_DIR);
    // English posts: `<slug>.tsx` with NO `.<loc>` before `.tsx`.
    const localeRe = new RegExp(`\\.(${LOCALES.join("|")})\\.tsx$`);
    const enFiles = files.filter((f) => f.endsWith(".tsx") && !localeRe.test(f));
    const posts = [];
    for (const f of enFiles) {
        const src = await readFile(path.join(POSTS_DIR, f), "utf8");
        const meta = parseMeta(src);
        if (!meta.slug) continue;
        posts.push({ ...meta, body: extractBody(src), file: f });
    }
    return posts;
}

// ─── JSX body validation (allow-list of tags used by existing posts) ──────────
// Disallow anything dynamic ({...} expressions other than the literal {" "}
// JSX-whitespace token, <script>, on*= handlers, etc.) so the generated body is
// safe to drop into a component verbatim.
const ALLOWED_TAGS = new Set([
    "p", "h2", "h3", "ul", "ol", "li", "strong", "em", "code", "a", "Link", "blockquote",
]);

function validateBody(body) {
    if (!body || body.length < 200) return "body too short";
    if (/<\s*script/i.test(body)) return "contains <script>";
    if (/\son[a-z]+\s*=/i.test(body)) return "contains an event handler attribute";
    // Reject JSX expression containers except the harmless whitespace token {" "}.
    const exprs = body.match(/\{[^}]*\}/g) || [];
    for (const e of exprs) {
        if (!/^\{\s*"[^"]*"\s*\}$/.test(e)) return `disallowed JSX expression: ${e.slice(0, 40)}`;
    }
    // Every tag name must be in the allow-list.
    const tags = body.match(/<\/?([A-Za-z][A-Za-z0-9]*)/g) || [];
    for (const t of tags) {
        const name = t.replace(/^<\/?/, "");
        if (!ALLOWED_TAGS.has(name)) return `disallowed tag <${name}>`;
    }
    return null; // valid
}

// ─── Prompts ──────────────────────────────────────────────────────────────────
function generationPrompt(samples, existingSlugs, allTags) {
    return `You are a senior writer for FileShrinking, a privacy-first, browser-based file-compression tool (images, video, audio, PDF — all processed client-side, nothing uploaded). Write ${COUNT} brand-new English blog post(s).

Match the EXISTING posts exactly in voice, depth, structure, length, and on-page SEO. Here are ${samples.length} real examples (study tone, body length ~1300-1800 words, the practical/honest voice, internal links, and heading structure). Each example shows its meta fields and its JSX body:

${JSON.stringify(samples, null, 2)}

STRICT REQUIREMENTS for each new post object:
- "slug": short, kebab-case, unique. MUST NOT be any of these existing slugs: ${JSON.stringify(existingSlugs)}
- "title": specific and useful (not clickbait), like the samples.
- "description": 1-2 sentences for the blog index card AND the meta description (150-160 chars ideal).
- "authorId": one of ${JSON.stringify(AUTHOR_IDS)} (use "maya" for technical/how-it-works pieces, "team" otherwise).
- "tags": array of 2-4 short topic tags, reusing existing tags where they fit: ${JSON.stringify([...new Set(allTags)])}.
- "readingMinutes": integer estimate (existing posts are 6-9).
- "body": the FULL article as a JSX fragment's inner content (do NOT wrap in <> </>, and do NOT include an <h1> — the title renders separately).

BODY JSX RULES — this is rendered as a React component, so the body MUST be valid JSX using ONLY this restricted set of elements (exactly like the samples):
  • <p>…</p> for paragraphs.
  • <h2 id="kebab-anchor">…</h2> and <h3 id="…">…</h3> for headings (always include a unique, kebab-case id attribute).
  • <ul><li>…</li></ul> (or <ol>) for lists.
  • <strong>…</strong>, <em>…</em>, <code>…</code> for inline emphasis/code.
  • Internal links to other pages on this site: <Link href="/some-path">text</Link> (the "Link" component, capital L — it is imported for you). Useful internal targets: /image-compressor, /video-compressor, /pdf-compressor, /audio-compressor, /compress-webp, /compress-avif, /blog/<an-existing-slug>.
  • External links: <a href="https://…" target="_blank" rel="noopener noreferrer">text</a>.
  • For HTML entities use the named/entity escapes the samples use (e.g. &rsquo; &mdash; &nbsp;), NOT raw curly-brace expressions.
  • Do NOT use any other tags, any className/style attributes, any {javascript expressions}, <img>, <script>, or event handlers. The ONLY brace token allowed is the JSX whitespace token {" "} between adjacent inline elements, exactly as the samples use it.

Write 1300-1800 words of genuinely useful, accurate content. Pick fresh, non-overlapping topics NOT already covered by the existing slugs. Each post must be a distinct topic. Link naturally to 2-3 relevant internal pages.

Call the submit_posts tool with exactly ${COUNT} post object(s).`;
}

function translationPrompt(localeName, posts) {
    return `Translate the following ${posts.length} blog post object(s) from English into ${localeName} for FileShrinking.

RULES:
- Translate these fields naturally and idiomatically: "title", "description", "tags" (translate each tag), and "body".
- Keep "slug" EXACTLY as given in English (do NOT translate it).
- Keep "authorId" and "readingMinutes" EXACTLY as given.
- In "body", preserve ALL JSX structure exactly: the same <h2 id="…">/<h3 id="…"> elements WITH THE SAME id values (do NOT translate ids), the same <ul>/<li>, <strong>, <em>, <code>, <Link>/<a> elements, and every link's href/target/rel attributes UNCHANGED (translate only the visible link text). Keep the {" "} whitespace tokens. Use the same restricted JSX subset — introduce no new tags or attributes.
- For internal <Link href="/x"> links, PREFIX the path with the locale: <Link href="/${"{LOC}"}/x">. (This rule's "{LOC}" is replaced below.)

For this translation the locale path prefix is: ${"/" }${"<<LOCALE_PREFIX>>"}

English posts:
${JSON.stringify(posts, null, 2)}

Call the submit_posts tool with exactly ${posts.length} translated post object(s).`;
}

// ─── Serialize a post object into a TSX module ────────────────────────────────
function tsString(s) {
    return JSON.stringify(String(s));
}

function renderModule(post, { localized }) {
    // Indent the body two levels (inside the fragment inside return()).
    const bodyIndented = post.body
        .split("\n")
        .map((l) => (l.trim() ? "      " + l : l))
        .join("\n");
    const tags = `[${post.tags.map(tsString).join(", ")}]`;
    return `import Link from "next/link";
import type { BlogPostMeta } from "@/lib/blog/types";

export const meta: BlogPostMeta = {
  slug: ${tsString(post.slug)},
  title: ${tsString(post.title)},
  description: ${tsString(post.description)},
  datePublished: ${tsString(post.datePublished)},
  dateModified: ${tsString(post.dateModified ?? post.datePublished)},
  authorId: ${tsString(post.authorId)},
  tags: ${tags},
  readingMinutes: ${Number(post.readingMinutes) || 6},
};

export default function Content() {
  return (
    <>
${bodyIndented}
    </>
  );
}
`;
}

// Localize internal <Link href="/x"> targets for a non-default locale, leaving
// <a href="http…"> external links and same-locale anchors alone. Idempotent
// safety net in case the model didn't prefix them.
function localizeLinks(body, loc) {
    return body.replace(
        /<Link href="\/((?!#)[^"]*)"/g,
        (full, p) => (p.startsWith(`${loc}/`) || p === loc ? full : `<Link href="/${loc}/${p}"`),
    );
}

// ─── Registry editing (English posts must be registered to appear/sitemap) ────
function camelIdent(slug) {
    return slug.replace(/[-.](\w)/g, (_, c) => c.toUpperCase()).replace(/\W/g, "");
}

function addToRegistry(src, newPosts) {
    let out = src;
    // 1) Add imports after the last existing post import line.
    const importLines = newPosts.map(
        (p) => `import * as ${camelIdent(p.slug)} from "@/components/blog/posts/${p.slug}";`,
    );
    const importRe = /import \* as \w+ from "@\/components\/blog\/posts\/[^"]+";\n/g;
    let lastImportEnd = 0;
    let m;
    while ((m = importRe.exec(src))) lastImportEnd = m.index + m[0].length;
    if (!lastImportEnd) throw new Error("Could not locate post imports in registry.ts");
    out = out.slice(0, lastImportEnd) + importLines.join("\n") + "\n" + out.slice(lastImportEnd);

    // 2) Add identifiers into the MODULES array (before its closing "].map").
    const anchor = "].map((m) => m as unknown as BlogPostModule);";
    const idx = out.indexOf(anchor);
    if (idx < 0) throw new Error("Could not locate MODULES array close in registry.ts");
    const entries = newPosts.map((p) => `  ${camelIdent(p.slug)},`).join("\n");
    out = out.slice(0, idx) + entries + "\n" + out.slice(idx);
    return out;
}

// ─── Run gen-i18n.mjs to rebuild posts.generated.ts from the new .<loc>.tsx ───
function runGenI18n() {
    return new Promise((resolve, reject) => {
        const p = spawn(process.execPath, [path.join(ROOT, "scripts/gen-i18n.mjs")], {
            cwd: ROOT,
            stdio: "inherit",
        });
        p.on("error", reject);
        p.on("exit", (code) =>
            code === 0 ? resolve() : reject(new Error(`gen-i18n.mjs exited ${code}`)),
        );
    });
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
    const english = await readEnglishPosts();
    const existingSlugs = english.map((p) => p.slug);
    const allTags = english.flatMap((p) => p.tags);

    // Two recent posts as the style reference. Sort by slug just for stability;
    // full body included so the model matches the JSX subset and length.
    const samples = english.slice(0, 2).map((p) => ({
        slug: p.slug, title: p.title, description: p.description,
        authorId: p.authorId, tags: p.tags, readingMinutes: p.readingMinutes,
        body: p.body,
    }));

    console.log(`→ Generating ${COUNT} new English post(s) with ${MODEL}…`);
    const generated = await claudePosts(generationPrompt(samples, existingSlugs, allTags));

    const today = new Date().toISOString().slice(0, 10);
    const seen = new Set(existingSlugs);
    const newPosts = [];
    for (const p of Array.isArray(generated) ? generated : [generated]) {
        if (!p || !p.slug || !p.body) { console.warn("  ⚠ skipping malformed post", p?.slug); continue; }
        if (seen.has(p.slug)) { console.warn(`  ⚠ duplicate slug "${p.slug}" — skipping`); continue; }
        const err = validateBody(p.body);
        if (err) { console.warn(`  ⚠ post "${p.slug}" failed body validation (${err}) — skipping`); continue; }
        seen.add(p.slug);
        newPosts.push({ ...p, datePublished: today, dateModified: today });
    }
    if (!newPosts.length) throw new Error("Model returned no usable new posts");
    console.log(`  ✓ ${newPosts.length} post(s): ${newPosts.map((p) => p.slug).join(", ")}`);

    // Translate into every locale (one call per locale).
    const translations = {}; // loc -> array aligned to newPosts
    for (const loc of LOCALES) {
        console.log(`→ Translating to ${LOCALE_NAMES[loc]} (${loc})…`);
        const prompt = translationPrompt(LOCALE_NAMES[loc], newPosts).replace(/<<LOCALE_PREFIX>>/g, loc);
        const arr = await claudePosts(prompt);
        translations[loc] = newPosts.map((en, i) => {
            const tr = (Array.isArray(arr) ? arr : []).find((t) => t && t.slug === en.slug) || arr[i] || {};
            const body = localizeLinks(tr.body || en.body, loc);
            const err = validateBody(body);
            if (err) {
                console.warn(`  ⚠ ${loc} translation of "${en.slug}" failed validation (${err}) — using English body`);
            }
            return {
                slug: en.slug,
                title: tr.title || en.title,
                description: tr.description || en.description,
                authorId: en.authorId,
                tags: Array.isArray(tr.tags) && tr.tags.length ? tr.tags : en.tags,
                readingMinutes: en.readingMinutes,
                datePublished: today,
                dateModified: today,
                body: err ? localizeLinks(en.body, loc) : body,
            };
        });
    }

    if (NO_WRITE) {
        console.log("\n--no-write: nothing written. Generated English posts:\n");
        console.log(JSON.stringify(newPosts, null, 2));
        return;
    }

    // Write English TSX modules.
    for (const p of newPosts) {
        await writeFile(postFile(p.slug), renderModule(p, { localized: false }));
        console.log(`  ✓ wrote components/blog/posts/${p.slug}.tsx`);
    }

    // Register the English posts (this is what surfaces them on /blog + sitemap).
    const reg = await readFile(REGISTRY_TS, "utf8");
    await writeFile(REGISTRY_TS, addToRegistry(reg, newPosts));
    console.log(`  ✓ registered ${newPosts.length} post(s) in lib/blog/registry.ts`);

    // Write per-locale TSX modules.
    for (const loc of LOCALES) {
        for (const p of translations[loc]) {
            await writeFile(postFile(p.slug, loc), renderModule(p, { localized: true }));
        }
        console.log(`  ✓ wrote ${translations[loc].length} ${loc} translation file(s)`);
    }

    // Rebuild the localized index (posts.generated.ts) from the filesystem.
    console.log("→ Running scripts/gen-i18n.mjs to rebuild posts.generated.ts…");
    await runGenI18n();

    console.log("\n✅ Done.");
}

main().catch((err) => {
    console.error("❌", err.message);
    process.exit(1);
});
